CREATE DATABASE BANGALORE;
DROP DATABASE BANGALORE;
USE BANGALORE;
CREATE TABLE METRO(STATION_NAME VARCHAR(30),
STATION_CODE VARCHAR(20),
LINE_COLOR VARCHAR(20),
LINE_NAME VARCHAR(20),
DISTANCE_BW_STATION VARCHAR(100),
OPERATING_HOURS VARCHAR(20),
FARE_INFORMATION VARCHAR(20),
ACCESSIBILITY_INFORMATION VARCHAR(20),
ROUTE_MAP VARCHAR(50),
MAINTENANCE_SCHEDULE VARCHAR(20));

ALTER TABLE METRO ADD COLUMN NAME_MATRO VARCHAR(20);
ALTER TABLE METRO RENAME COLUMN STATION_CODE TO STATION_CODENUM;
ALTER TABLE METRO DROP COLUMN DISTANCE_BW_STATION;
INSERT INTO METRO VALUES('UNION SQUARE','USQ','#FF0000','RED LINE','RAJAJINAGAR TO MEJESTIC','Weekdays: 6:00 AM - 11:00 PM, Weekends: 7:00 AM - 10:00 PM','FARE RULE','elevators, ramps, tactile paving metro system',' layout, including station locations, connecting lines, and important landmarks.','Facilities','EXPRESS');
SELECT *  FROM METRO;
ALTER TABLE METRO MODIFY COLUMN OPERATING_HOURS VARCHAR(100);
ALTER TABLE METRO MODIFY COLUMN ROUTE_MAP VARCHAR(100);
ALTER TABLE METRO MODIFY COLUMN ACCESSIBILITY_INFORMATION VARCHAR(100);
ALTER TABLE METRO RENAME METRO_BANGALORE;
ALTER TABLE METRO_BANGALORE CHANGE  MAINTENANCE_SCHEDULE MAINTENANCE_SCHEDUL VARCHAR(25);

CREATE TABLE MOVIE(MovieID INT,
TITLE VARCHAR(30),
RELESE_YEAR VARCHAR(30),
GENRE VARCHAR(30),
DIRECTOR VARCHAR(30),
HERO_NAME VARCHAR(30),
HEROIN_NAME VARCHAR(30),
RATINGS BOOLEAN,
RUNTIME_MIN VARCHAR(30),
 LANGUAGE VARCHAR(30));
 ALTER TABLE MOVIE RENAME MOVIE_INFORMATION;
 ALTER TABLE MOVIE_INFORMATION ADD COLUMN RELESE_DATE VARCHAR(20);
 ALTER TABLE MOVIE_INFORMATION RENAME COLUMN  RELESE_YEAR TO RELEASE1_YEAR;
 ALTER TABLE MOVIE_INFORMATION DROP COLUMN DIRECTOR;
 ALTER TABLE MOVIE_INFORMATION CHANGE RUNTIME_MIN RUNTIME_MINUTE VARCHAR(30);
 INSERT INTO MOVIE_INFORMATION VALUES (1,'The Shawshank Redemption','1994','Drama','YAHS','RADHIKA',TRUE,'3 HOURS','KANNADA','MONDAY');
 SELECT * FROM MOVIE_INFORMATION;
 
 CREATE TABLE MALLS(MALLID INT,
 MallName VARCHAR(50),
 Location VARCHAR(50),
 TotalStores INT,
 TotalFloors INT,
 ParkingCapacity INT,
 YearBuilt INT,
 AnchorStore VARCHAR(100),
 MallType VARCHAR(50));
 ALTER TABLE MALLS RENAME MALL1;
 ALTER TABLE MALL1 ADD COLUMN MALL_LOCATION VARCHAR(20);
 ALTER TABLE MALL1 RENAME COLUMN MallName to MALL_NAME;
 ALTER TABLE MALL1 DROP COLUMN TotalFloors;
 ALTER TABLE MALL1 CHANGE MallType MALL_TYPE VARCHAR(30);
 INSERT INTO MALL1 VALUES(1,'ORION MALL','BANAGALORE ',50,500,2015, 'MacyS',   'Shopping Center','123 MAIN STREET');
 SELECT * FROM MALL1;

CREATE TABLE  Resorts(ResortID INT PRIMARY KEY,
    ResortName VARCHAR(255),
    Location VARCHAR(255),
    Rating DECIMAL(3, 1),
    TotalRooms INT,
    TotalPools INT,
    TotalRestaurants INT,
    SpaAvailable BOOLEAN,
    Beachfront BOOLEAN,
    SkiResort BOOLEAN,
    GolfCourse BOOLEAN
);

ALTER TABLE Resorts RENAME RESORT_NAME;
 ALTER TABLE RESORT_NAME ADD COLUMN RESORT_LOCATION VARCHAR(20);
 ALTER TABLE RESORT_NAME RENAME COLUMN ResortName to RESTORANT_NAME;
  ALTER TABLE RESORT_NAME DROP COLUMN TotalPools;
  ALTER TABLE RESORT_NAME CHANGE GolfCourse GOLF_COURSE VARCHAR(30);
 INSERT INTO RESORT_NAME VALUES(1,'Paradise Resort','123 Beachfront Avenue',4.2,7,1,1,1,1,0,'BANGALORE');
 SELECT * FROM RESORT_NAME;
 
 CREATE TABLE Restaurants (
    RestaurantID INT,
    RestaurantName VARCHAR(255),
    CuisineType VARCHAR(100),
    Address VARCHAR(255),
    City VARCHAR(100),
    State VARCHAR(50),
    ZipCode VARCHAR(20),
    Rating INT,
    Capacity INT,
    OpeningHours VARCHAR(255)
);
ALTER TABLE Restaurants RENAME RESTAURANT_NAME;
ALTER TABLE RESTAURANT_NAME ADD COLUMN RESTAURANT_LOCATION VARCHAR(20);
 ALTER TABLE RESTAURANT_NAME RENAME COLUMN RestaurantName to RESTAURANT_NAME;
  ALTER TABLE RESTAURANT_NAME DROP COLUMN City;
  ALTER TABLE RESTAURANT_NAME CHANGE OpeningHours OPENING_HOURS VARCHAR(30);
  
 INSERT INTO  RESTAURANT_NAME VALUES(1, 'The Bistro', 'French', '123 Main Street', 'StateName', '12345', 4, 50, 'Mon-Sat: 11:00 AM - 9:00 PM','CITYNAME');
 SELECT * FROM RESTAURANT_NAME;
 
 
 CREATE TABLE Showrooms (
    ShowroomID INT PRIMARY KEY,
    ShowroomName VARCHAR(255),
    Location VARCHAR(255),
    ShowroomType VARCHAR(100),
    Capacity INT,
    ShowroomSizeSqFt DECIMAL(10, 2),
    OperatingHours VARCHAR(255),
    ContactPhone VARCHAR(20),
    ContactEmail VARCHAR(255),
    ManagerName VARCHAR(100)
);
ALTER TABLE Showrooms RENAME SHOWROOM_DETAILS;
ALTER TABLE SHOWROOM_DETAILS ADD COLUMN SHOWROOM_TIMINGS VARCHAR(20);
ALTER TABLE SHOWROOM_DETAILS RENAME COLUMN ShowroomName TO SHOWROOM_NAME;
ALTER TABLE SHOWROOM_DETAILS DROP COLUMN Capacity;
ALTER TABLE SHOWROOM_DETAILS CHANGE ManagerName MANAGER_NAME VARCHAR(30);
INSERT INTO SHOWROOM_DETAILS VALUES (1, 'TechHub Electronics Showroom', '123 Main Street, CityName', 'Electronics',1500.00, 'Mon-Fri: 9:00 AM - 7:00 PM', '+1234567890', 'info@techhub.com', 'John Doe','9:30AM-9:30PM');
SELECT * FROM SHOWROOM_DETAILS;